
config:
  envs:
    discovery: k8s
  zookeeper:
    schema: openim
    zkAddr:
      - 127.0.0.1:12181
    username: ""
    password: ""

  chatApi:
    openImChatApiPort: [ 80 ]
    listenIP:

  adminApi:
    openImAdminApiPort: [ 80 ]
    listenIP:

  rpc:
    registerIP:                            #作为rpc启动时，注册到zookeeper的IP，api/gateway能访问到此ip和对应的rpcPort中的端口
    listenIP:                               #默认为0.0.0.0

  rpcPort:
    openImAdminPort: [ 80 ]
    openImChatPort: [ 80 ]
  rpcRegisterName:
    openImAdminName: openimchat-admin-rpc:80
    openImChatName: openimchat-chat-rpc:80

  # 没有配置表示和OpenIM一致
  log:
    storageLocation: ../logs/           #存放目录
    rotationTime: 24                    #日志旋转时间
    remainRotationCount: 2              #日志数量
    remainLogLevel: 6                   #日志级别 6表示全都打印，
    isStdout: true
    isJson: false
    withStack: false

  secret: openIM123
  tokenPolicy:
    expire: 86400

  # Verification code settings
  verifyCode:
    validTime: 300 # Verification code valid time in seconds
    validCount: 5 # Number of times a verification code is valid
    uintTime: 86400 # Time unit for verification code
    maxCount: 10 # Maximum number of verification codes in a time unit
    superCode: "666666" # Super verification code (used only when `use` is empty)
    len: 6 # Length of the verification code
    use: "" # Service used for verification code (e.g., "ali")
    # Aliyun SMS service configuration
    ali:
      endpoint: "dysmsapi.aliyuncs.com"
      accessKeyId: ""
      accessKeySecret: ""
      signName: ""
      verificationCodeTemplateCode: ""
    # Email service configuration
    mail:
      title: ""
      senderMail: "" # Email address of the sender
      senderAuthorizationCode: "" # Authorization code for the sender's email
      smtpAddr: "smtp.qq.com" # SMTP server address
      smtpPort: 465 # SMTP server port for email sending

  # 获取ip的header,没有配置直接获取远程地址
  #proxyHeader: "X-Forwarded-For"

  adminList:
    - adminID:
      nickname:
      imAdmin:
    - adminID:
      nickname:
      imAdmin:
    - adminID:
      nickname:
      imAdmin:

  chatAdmin:
    - adminID: chatAdmin
      nickname: chatAdmin
      imAdmin: imAdmin

  openIMUrl: "http://openimserver-openim-api"

  redis:
    address: [ im-redis-master:6379 ]
    username:
    password: openIM123

  # liveKit:
  #   liveKitUrl: "ws://172.28.0.1:7880" # LIVEKIT_URL, LiveKit server address and port
  #   key: "APIDXJxJeCL8haY" # LIVEKIT_API_KEY
  #   secret: "ak1qulJ3nfXeflQHWBdmQDc4js4ueMc5OnxoORVJC2xA" # LIVEKIT_API_SECRET

  mongo:
    uri: ''

    # List of MongoDB server addresses.
    # Used for constructing the MongoDB URI if 'uri' above is empty.
    # For a standalone setup, specify the address of the single server.
    # For a sharded cluster, specify the addresses of the Mongos servers.
    # Example: [ '172.28.0.1:37017', '172.28.0.2:37017' ]
    # Default MongoDB database name
    # Maximum connection pool size
    address: [ im-mongodb:27017 ]
    database: openim_v3
    username: openIM
    password: openIM123
    maxPoolSize: 100
