#This configuration file is used to override the use of the value.yaml variable.
#Currently, only the configuration with ingressName as nginx is provided.
#If it is another gateway such as istio or treafik, please modify the corresponding gateway requirements
image:
  # registry.cn-hangzhou.aliyuncs.com/openimsdk/admin-api
  repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/chat-api-admin
  pullPolicy: Always
  tag: "release-v1.6"
ingress:
  enabled: true
  className: "nginx"
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
  hosts:
    - host: openim1.server.top
      paths:
        - path: /complete_admin(/|$)(.*)
          pathType: ImplementationSpecific
  tls:
    - secretName: webapitls  #your hostname tls
      hosts:
        - openim1.server.top

chat-api:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/chat-api-chat
    pullPolicy: Always
    tag: "release-v1.6"
  ingress:
    enabled: true
    className: "nginx"
    annotations:
      nginx.ingress.kubernetes.io/use-regex: "true"
      nginx.ingress.kubernetes.io/rewrite-target: /$2
    hosts:
      - host: openim1.server.top
        paths:
          - path: /chat(/|$)(.*)
            pathType: ImplementationSpecific
    tls:
      - secretName: webapitls  #your hostname tls
        hosts:
          - openim1.server.top

admin-rpc:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/chat-rpc-admin
    pullPolicy: Always
    tag: "release-v1.6"

chat-rpc:
  image:
    repository: registry.cn-hangzhou.aliyuncs.com/openimsdk/chat-rpc-chat
    pullPolicy: Always
    tag: "release-v1.6"
