{{- if .Values.global.monitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  labels:
    release: kube-prometheus-stack
  name: {{ include "openim-rpc-third.fullname" . }}
spec:
  endpoints:
    - interval: 15s
      port: metrics-port
  selector:
    matchLabels:
      app.kubernetes.io/name: openim-rpc-third
{{- end }}