name: Helm Charts CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up Kubernetes-in-Docker (kind)
      uses: helm/kind-action@v1.1.0

    - name: Install Helm
      uses: azure/setup-helm@v1
      with:
        version: '3.x'

    - name: Create Kubernetes Cluster
      run: |
        kind create cluster
        kubectl cluster-info

    - name: Install OpenIM Middleware
      run: |
        # Install MySQL
        helm install im-mysql infra/mysql -f infra/mysql-config.yaml -n openim

        # Install Kafka
        helm install im-kafka infra/kafka -f infra/kafka-config.yaml -n openim

        # Install MinIO
        helm install im-minio infra/minio -f infra/minio-config.yaml -n openim

        # Install MongoDB
        helm install im-mongodb infra/mongodb -f infra/mongodb-config.yaml -n openim

        # Install Redis
        helm install im-redis infra/redis -f infra/redis-config.yaml -n openim

    - name: Install OpenIM Services
      run: |
        # OpenIM Server Service 安装
        helm install openimserver ./openim/openim-server/ -f k8s-open-im-server-config.yaml -f config-imserver.yaml -f notification.yaml -n openim

        # OpenIM Chat Service 安装
        helm install openimchat ./openim/openim-chat/ -f k8s-chat-server-config.yaml -f config-chatserver.yaml -n openim

        # Web Frontend 安装
        helm install imwebfront ./openim/webfront/ -f k8s-webfront-config.yaml -n openim

        # Admin Frontend 安装
        helm install imadminfront ./openim/adminfront/ -f k8s-adminfront-config.yaml -n openim

    - name: Test Installation
      run: |
        # 这里添加一些基本的测试命令，例如检查 Pod 状态
        kubectl get pods -n openim

    - name: Cleanup
      if: always()
      run: |
        kind delete cluster
